# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: dotnet-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-1337app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-1337app
  template:
    metadata:
      labels:
        app: dotnet-1337app
    spec:
      containers:
      - name: server
        image: dotnet-hello-world
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
